name: LagoonBox-DeszczFragmentow
version: '1.0'
main: pl.podateK.DeszczFragmentow.Main
api-version: '1.18'
commands:
  deszcz:
    permission: lagoonbox.deszcz.command
    aliases: [deszczfragmentow, rain]
    usage: /<command>